name: Build and Deploy

on:
  workflow_dispatch:


jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: build and publish ghcr.io docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/johnsonran/mosdns:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max